spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unimaster
    username: developer
    password: 123456789
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true